### ISSUE TITLE
XLSX2JSON parse data incorrect

### ISSUE THREAD

**Issue by boldak** [kpi-wdc/wdc#135]
Неправильно парсятся данные, которые приходят в xlsx файле.

1. Послал данные:

![image](https://cloud.githubusercontent.com/assets/2777363/6821746/a6e26a52-d2e2-11e4-98e4-5a4f99fe7fd4.png)

![image](https://cloud.githubusercontent.com/assets/2777363/6821752/bb71f532-d2e2-11e4-9f50-39ea9593553d.png)

Получил результат:

{
  "name": "GTrUAPL20052013",
  "metadata": {
    "note": "test",
    "label": "Sustainable Development Indexes Ukraine 2005-2013",
    "updated": "2014-12-15",
    "status": "e",
    "source": "World Data Center of Ukraine",
    "dimension": {
      "id": [
        "row",
        "column"
      ],
      "role": {
        "geo": [
          "row"
        ],
        "time": [
          "row"
        ],
        "metric": [
          "row"
        ]
      },
      "size": [
        2,
        5
      ],
      "row": {
        "label": "Row",
        "category": {
          "index": {
            "r1": 4,
            "r2": 9
          },
          "label": {
            "r1": "r1",
            "r2": "r2"
          }
        }
      },
      "column": {
        "label": "Column",
        "category": {
          "index": {
            "c1": 1,
            "c2": 3,
            "c3": 5,
            "c4": 7,
            "c5": 9
          },
          "label": {
            "c1": "c1",
            "c2": "c2",
            "c3": "c3",
            "c4": "c4",
            "c5": "c5"
          }
        }
      }
    }
  },
  "value": [
    11,
    11,
    12,
    12,
    13,
    11,
    11,
    12,
    12,
    13
  ],
  "createdAt": "2015-03-25T09:18:07.094Z",
  "updatedAt": "2015-03-25T09:18:07.094Z",
  "id": "55127d4fb6f0ccc41372ca43"
}

Правильно должно быть так:
{
  "name": "GTrUAPL20052013",
  "metadata": {
    "note": "test",
    "label": "Sustainable Development Indexes Ukraine 2005-2013",
    "updated": "2014-12-15",
    "status": "e",
    "source": "World Data Center of Ukraine",
    "dimension": {
      "id": [
        "row",
        "column"
      ],
      "role": {
        "geo": [
          "row"
        ],
        "time": [
          "row"
        ],
        "metric": [
          "row"
        ]
      },
      "size": [
        2,
        5
      ],
      "row": {
        "label": "Row",
        "category": {
          "index": {
            "r1": 0,
            "r2": 1
          },
          "label": {
            "r1": "r1",
            "r2": "r2"
          }
        }
      },
      "column": {
        "label": "Column",
        "category": {
          "index": {
            "c1": 0,
            "c2": 1,
            "c3": 2,
            "c4": 3,
            "c5": 4
          },
          "label": {
            "c1": "c1",
            "c2": "c2",
            "c3": "c3",
            "c4": "c4",
            "c5": "c5"
          }
        }
      }
    }
  },
  "value": [
    11,
    12,
    13,
    14,
    15,
    21,
    22,
    23,
    24,
    25
  ],
  "createdAt": "2015-03-25T09:18:07.094Z",
  "updatedAt": "2015-03-25T09:18:07.094Z",
  "id": "55127d4fb6f0ccc41372ca43"
}

**Comment by sochka** [comment]
I think this was fixed by @boldak

**Comment by batytskyy** [comment]
It was, but by @Serhii-Podvysotskyi :)
