### ISSUE TITLE
Cannot upload xlsx data to dps

### ISSUE THREAD

**Issue by boldak** [kpi-wdc/wdc#144]
When upload file dataset collection is empty

**Comment by batytskyy** [comment]
What is the name of xlsx file you have tried to upload? Does up-loader work for some other xlsx file?

**Comment by batytskyy** [comment]
These two files: `gl2013_2005.xls` and  `CQLCSL2013.xlsx` incorrect format, so they can't be parsed. For other files dataset upload works as expected.
