### ISSUE TITLE
Create widgetTranslate service, directive and filter 

### ISSUE THREAD

**Issue by sochka** [kpi-wdc/wdc#181]
This would allow writing `<widget-translate>TRANSLATION_ID</widget-translate>` instead of `<translate>WIDGET.WIDGET-NAME.TRANSLATION_ID</translate>`

**Comment by sashasochka** [comment]
Only `widget-translate` directive is created (not as complete as original `translate` directive)

**Comment by sashasochka** [comment]
This means you can use `<widget-translate>TRANSLATION_ID</widget-translate>` instead of `<widget>WIDGET.WIDGET_NAME.TRANSLATION_ID</widget>` now.
